### ISSUE TITLE
latest commit "e75aec3": Crash when using a Textralabel with wrap and multiple line breaks in a row

### ISSUE THREAD

**Issue by Trurl101** [tommyettinger/textratypist#21]
I used the latest commit version with jitpack: e75aec3 

Using a text with wrapping and two or more line breaks in a row "\n\n" results in a crash. It works in 1.1.0 without crashing. Making a space between the line breaks "\n \n" prevents the crash.

```
TextraLabel label = new TextraLabel("abc\n\nxyz", style);
label.setPosition(800, 400);
label.setWrap(true);
```

```
Exception in thread "main" java.lang.IllegalStateException: Array is empty.
        at com.badlogic.gdx.utils.LongArray.peek(LongArray.java:281)
        at com.github.tommyettinger.textra.Font.regenerateLayout(Font.java:6992)
        at com.github.tommyettinger.textra.TextraLabel.layout(TextraLabel.java:535)
        at com.badlogic.gdx.scenes.scene2d.ui.Widget.validate(Widget.java:88)
        at com.github.tommyettinger.textra.TextraLabel.draw(TextraLabel.java:275)
        at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
        at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
        at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
        at de.erdenkriecher.hasi.ScreenAbstract.render(ScreenAbstract.java:133)
        at com.badlogic.gdx.Game.render(Game.java:48)
        at de.erdenkriecher.hasi.GameAbstract.render(GameAbstract.java:118)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:432)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:181)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:153)
        at de.erdenkriecher.magicalchemist.desktop.DesktopLauncher.main(DesktopLauncher.java:23)
```

**Comment by tommyettinger** [comment]
Huh, I am not sure when I would have changed this. Looking into this now.
